document.writeln("<style>");
document.writeln("body,td{font-size:12px}");
document.writeln(".copyright263{COLOR: #444444;line-height: 18px;}");
document.writeln(".copyright263 A:link {COLOR: #444444; text-decoration: underline}");
document.writeln(".copyright263 A:visited {COLOR: #444444; text-decoration: underline}");
document.writeln(".copyright263 A:hover {COLOR: #444444; text-decoration: none} ");
document.writeln(".copyright263 A:active {COLOR: #444444; text-decoration:underline} ");
document.writeln("<\/style>");
document.writeln("<hr width=\"840\" size=\"1\">");
document.writeln("<table width=\"600\" border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\">");
document.writeln("  <tr> ");
document.writeln("    <td width=\"100\"><a href=\"http:\/\/www.net263.com\" target=\"_blank\"><img src=\"http:\/\/www.net263.com\/js\/s_263logo.gif\" width=\"100\" height=\"50\" border=\"0\"><\/a><\/td>");
document.writeln("    <td width=\"20\"><\/td>");
document.writeln("    <td class=\"copyright263\"><a href=\"http:\/\/www.net263.com\/about\/about263.htm\">关于263<\/a> | <a href=\"http:\/\/www.net263.com\/about\/resource_job.htm\">招聘信息<\/a> | <a href=\"http:\/\/www.net263.com\/about\/contact.htm\">联系我们<\/a> | <a href=\"http:\/\/www.net263.com\/common\/sitemap.htm\">网站地图<\/a> | ");
document.writeln("      <a href=\"http:\/\/www.net263.com\/common\/copyright.htm\">版权声明<\/a><br>");
document.writeln("      Copyright&copy; 1998-2007&nbsp;&nbsp;版权所有&nbsp;263网络通信<br> 增值电信业务经营许可证B2-20040046号<\/td>");
document.writeln("    <td width=\"80\" class=\"copyright263\"><a href=\"http:\/\/www.bj.cyberpolice.cn\/index.htm\" target=\"_blank\"><img src=\"http:\/\/www.net263.com\/js\/net110.gif\" width=\"80\" height=\"37\" border=\"0\"><\/a><\/td>");
document.writeln("  <\/tr>");
document.writeln("<\/table>");
document.writeln("<br>");