document.write("<style>");
document.write("#topmenu{");
document.write("height:28px;");
document.write("width:100%;white-space:nowrap;");
document.write("background-image: url(http:\/\/www.net263.com\/js\/topmenu_bg.gif);");
document.write("background-repeat : repeat-x;");
document.write("padding-left: 280px;");
document.write("padding-top: 5px;");
document.write("padding-bottom: 5px;");
document.write("COLOR: #DDDDDD;line-height: 18px;}");
document.write("body,td{font-size:12px}");
document.write("A.topmenu263:link {COLOR: #DDDDDD; text-decoration: none}");
document.write("A.topmenu263:visited {COLOR: #DDDDDD; text-decoration: none}");
document.write("A.topmenu263:hover {COLOR: #DDDDDD; text-decoration: underline} ");
document.write("A.topmenu263:active {COLOR: #DDDDDD; text-decoration:none} ");
document.write("");
document.write("A.top_submenu:link {");
document.write("	border-bottom: #eeeeee 1px solid;");
document.write("	display: block; ");
document.write("	padding-left: 10px; ");
document.write("	background: #444444; ");
document.write("	vertical-align: middle; ");
document.write("	width: auto; color: #ffffff;");
document.write("	padding-top: 3px; ");
document.write("	height: 24px; ");
document.write("	text-align: left; ");
document.write("	text-decoration: none");
document.write("}");
document.write("A.top_submenu:visited {");
document.write("	border-bottom: #eeeeee 1px solid;");
document.write("	display: block; ");
document.write("	padding-left: 10px; ");
document.write("	background: #444444; ");
document.write("	vertical-align: middle; ");
document.write("	width: auto; ");
document.write("	color: #ffffff;");
document.write("	padding-top: 3px; ");
document.write("	height: 24px; ");
document.write("	text-align: left; ");
document.write("	text-decoration: none");
document.write("}");
document.write("A.top_submenu:hover {");
document.write("	font-weight: bold; ");
document.write("	background: #A3181B; ");
document.write("	color: #ffffff; ");
document.write("	text-decoration: none");
document.write("}");
document.write("<\/style>");
document.write("<div id=\"topmenu\">");
document.write("<a target=\"_blank\" href=\"http:\/\/www.net263.com\" class=\"topmenu263\" onMouseOver=\"top_submenu1.style.display=\'none\'; top_submenu2.style.display=\'none\'\">263首页<\/a> | ");
document.write("<a target=\"_blank\" class=\"topmenu263\" href=\"http:\/\/www.net263.com\/about\/about263.htm\" onMouseOver=\"top_submenu1.style.display=\'none\'; top_submenu2.style.display=\'none\'\">关于263<\/a> | ");
document.write("<a target=\"_blank\" class=\"topmenu263\" href=\"http:\/\/www.net263.com\/data\/news\/index.htm\" onMouseOver=\"top_submenu1.style.display=\'none\'; top_submenu2.style.display=\'none\'\">媒体中心<\/a> | ");
document.write("<a target=\"_blank\" class=\"topmenu263\" href=\"http:\/\/www.net263.com\/service\/service.htm\" onMouseOver=\"top_submenu1.style.display=\'none\'; top_submenu2.style.display=\'none\'\">服务与支持<\/a> | ");
document.write("<a target=\"_blank\" class=\"topmenu263\" href=\"http:\/\/et.net263.com\" onMouseOver=\"top_submenu1.style.display=\'none\'; top_submenu2.style.display=\'none\'\">ET网络视频电话<\/a> | ");
document.write("<div id=\"top_submenu1\" style=\"padding-top: 20px;position:absolute; width:69px; height:60px; z-index:1; display:none;\" onMouseOver=\"this.style.display=\'\'\" onMouseOut=\"this.style.display=\'none\'\">");
document.write("<a target=\"_blank\" href=\"http:\/\/mail.263.net\" class=\"top_submenu\">个人邮件<\/a>");
document.write("<a target=\"_blank\" href=\"http:\/\/gmail.263.net\" class=\"top_submenu\">企业邮件<\/a>");
document.write("<\/div>");
document.write("<a class=\"topmenu263\" href=\"http:\/\/www.263.net\" onMouseOver=\"top_submenu1.style.display=\'\'; top_submenu2.style.display=\'none\'\">天下邮<\/a> | ");
document.write("<div id=\"top_submenu2\" style=\"padding-top: 20px;position:absolute; width:69px; height:60px; z-index:1; display:none;\" onMouseOver=\"this.style.display=\'\'\" onMouseOut=\"this.style.display=\'none\'\">");
document.write("<a target=\"_blank\" href=\"http:\/\/96446.263.net\" class=\"top_submenu\">96446<\/a>");
document.write("<a target=\"_blank\" href=\"http:\/\/95050.263.net\" class=\"top_submenu\">95050<\/a>");
document.write("<a target=\"_blank\" href=\"http:\/\/isp.263.net\" class=\"top_submenu\">拨号上网<\/a>");
document.write("<\/div>");
document.write("<a class=\"topmenu263\" href=\"#\" onMouseOver=\"top_submenu2.style.display=\'\'; top_submenu1.style.display=\'none\'\">通信增值<\/a> | ");
document.write("<a target=\"_blank\" class=\"topmenu263\" href=\"http:\/\/www.doshow.com.cn\" onMouseOver=\"top_submenu1.style.display=\'none\'; top_submenu2.style.display=\'none\'\">DoShow社区<\/a> | ");
document.write("<a target=\"_blank\" class=\"topmenu263\" href=\"http:\/\/sms.263.net\" onMouseOver=\"top_submenu1.style.display=\'none\'; top_submenu2.style.display=\'none\'\">无线<\/a> | ");
document.write("<a target=\"_blank\" class=\"topmenu263\" href=\"http:\/\/www.263.com\" onMouseOver=\"top_submenu1.style.display=\'none\'; top_submenu2.style.display=\'none\'\">263在线<\/a> | ");
document.write("<\/div>");
document.write("");