document.write("<style type=\"text/css\">");
document.write("td{font-size:12px;line-height:150%;color:#353535} ");
document.write("<!--");
document.write("#newtop1 {");
document.write("	FONT-SIZE: 12px; COLOR: #4D0095; LINE-HEIGHT: 160%; TEXT-DECORATION: none");
document.write("}");
document.write("#newtop1 A {");
document.write("	FONT-SIZE: 12px; COLOR: #4D0095; LINE-HEIGHT: 160%; TEXT-DECORATION: none");
document.write("}");
document.write("#newtop1 A:hover {");
document.write("	FONT-SIZE: 12px; COLOR: #ff9900; LINE-HEIGHT: 160%; TEXT-DECORATION: underline");
document.write("}");
document.write("<br />");
document.write("#newtop2 {");
document.write("	FONT-SIZE: 12px; COLOR: #070097; LINE-HEIGHT: 160%; TEXT-DECORATION: none");
document.write("}");
document.write("#newtop2 A {");
document.write("	FONT-SIZE: 12px; COLOR: #070097; LINE-HEIGHT: 160%; TEXT-DECORATION: none");
document.write("}");
document.write("#newtop2 A:hover {");
document.write("	FONT-SIZE: 12px; COLOR: #ff3300; LINE-HEIGHT: 160%; TEXT-DECORATION: underline");
document.write("}");
document.write(".style1 {color: #B916FE}");
document.write("-->");
document.write("</style>");
document.write("</head>");
document.write("<body>");
document.write("<table width=\"760\" border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\">");
document.write("  <tr>");
document.write("    <td width=\"11\"><img src=\"http://www.topstudy.com.cn/images/newtop1.gif\" width=\"11\" height=\"79\"></td>");
document.write("    <td valign=\"top\" background=\"http://www.topstudy.com.cn/images/newtop3.gif\">      <table width=\"100%\" height=\"53\"  border=\"0\" cellpadding=\"0\" cellspacing=\"0\">");
document.write("        <tr>");
document.write("          <td align=\"center\" valign=\"middle\"><table width=\"100%\" height=\"21\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" id=\"newtop1\">");
document.write("            <tr>");
document.write("              <td align=\"center\"><a href=\"http://www.topstudy.com.cn/\" target=_blank>首页</a>| <a href=\"http://article.topstudy.com.cn/\" target=_blank>新闻</a> | <a href=\"http://gaokao.topstudy.com.cn/\" target=_blank>高考</a> | <a href=\"http://zikao.topstudy.com.cn/\" target=_blank>自考</a> | <a href=\"http://minxiao.topstudy.com.cn/\" target=_blank>民办</a> | <a href=\"http://yjs.topstudy.com.cn/\" target=_blank>研究生</a> | <a href=\"http://kaoyan.topstudy.com.cn\" target=_blank>考研</a> | <a href=\"http://mba.topstudy.com.cn/\" target=_blank>商学院</a> | <a href=\"http://abroad.topstudy.com.cn/\" target=_blank>留学</a> | <a href=\"http://zw.topstudy.com.cn/\" target=_blank>中外合作</a> | <a href=\"http://tour.topstudy.com.cn/\" target=_blank>游学</a> | <a href=\"http://www.topstudy.com.cn/main/kaoshi/\" target=_blank>考试</a> | <a href=\"http://www.topstudy.com.cn/main/xuexiaozonghui/\" target=_blank>学校</a> | <a href=\"http://www.topstudy.com.cn/main/kechengzonghui/\" target=_blank>课程</a> | <a href=\"http://bbs.topstudy.com.cn/\" target=_blank>社区</a> | <a href=\"http://www.topstudy.com.cn/main/kefu/\" target=_blank>客服中心</a></td>");
document.write("            </tr>");
document.write("<table width=\"99%\" height=\"1\"  border=\"0\" cellpadding=\"0\" cellspacing=\"0\"><tr><td background=\"http://www.topstudy.com.cn/images/newtop4.gif\"></td></tr></table> ");
document.write("            <table width=\"100%\" height=\"21\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" id=\"newtop1\">");
document.write("              <tr>");
document.write("                <td align=\"center\"><a href=\"http://article.topstudy.com.cn/campus/\" target=_blank>校园</a>| <a href=\"http://waiyu.topstudy.com.cn/\" target=_blank>外语</a> | <a href=\"http://ielts.topstudy.com.cn/\" target=_blank>雅思</a> | <a href=\"http://www.topstudy.com.cn/main/toefl/\" target=_blank>托福</a> | <a href=\"http://waiyu.topstudy.com.cn/kouyu/\" target=_blank>口语 </a> | <a href=\"http://waiyu.topstudy.com.cn/xiaoyuzhong/\" target=_blank>多语种</a> | <a href=\"http://it.topstudy.com.cn/\" target=_blank>I&nbsp; T</a> | <a href=\"http://zgrz.topstudy.com.cn/\" target=_blank>认&nbsp; 证</a>&nbsp;| <a href=\"http://manager.topstudy.com.cn\" target=_blank>管理</a> | <a href=\"http://zyjy.topstudy.com.cn/\" target=_blank>职业教育</a> | <a href=\"http://job.topstudy.com.cn/\" target=_blank>招聘</a> | <a href=\"http://cg.topstudy.com.cn\" target=_blank>成高</a> | <a href=\"http://ck.topstudy.com.cn\" target=_blank>财会</a> | <a href=\"http://wenti.topstudy.com.cn\" target=_blank>文体</a> | <a href=\"http://yuancheng.topstudy.com.cn/\" target=_blank>远程</a> | <a href=\"http://www.51test.net/\" target=_blank>无忧考网</a> </td>");
document.write("              </tr>");
document.write("            </table></td>");
document.write("        </tr>");
document.write("      </table>      ");
document.write("      <table width=\"100%\" height=\"25\"  border=\"0\" cellpadding=\"0\" cellspacing=\"0\" id=\"newtop2\">");
document.write("        <tr>");
document.write("          <td align=\"center\"> <strong>全国分站：</strong> |<a href=\"http://bj.topstudy.com.cn/\" target=_blank>北京</a> |<a href=\"http://sh.topstudy.com.cn/\" target=_blank>上海</a> |<a href=\"http://gz.topstudy.com.cn/\" target=_blank>广州</a> |<a href=\"http://cc.topstudy.com.cn/\" target=_blank>长春</a> |<a href=\"http://cq.topstudy.com.cn/\" target=_blank>重庆</a> |<a href=\"http://cs.topstudy.com.cn/\" target=_blank>长沙</a> |<a href=\"http://dl.topstudy.com.cn/\" target=_blank>大连</a> |<a href=\"http://hrb.topstudy.com.cn/\" target=_blank>哈尔滨</a> |<a href=\"http://hz.topstudy.com.cn/\" target=_blank>杭州</a> |<a href=\"http://ha.topstudy.com.cn/\" target=_blank>河南</a> |<a href=\"http://nj.topstudy.com.cn/\" target=_blank>南京</a> |<a href=\"http://qd.topstudy.com.cn/\" target=_blank>青岛</a> |<a href=\"http://sjz.topstudy.com.cn/\" target=_blank>石家庄</a> |<a href=\"http://sy.topstudy.com.cn/\" target=_blank>沈阳</a> |<a href=\"http://sz.topstudy.com.cn/\" target=_blank>深圳</a> |<a href=\"http://tj.topstudy.com.cn/\" target=_blank>天津</a> |<a href=\"http://xa.topstudy.com.cn/\" target=_blank>西安</a> |<a href=\"http://wh.topstudy.com.cn/\" target=_blank>武汉</a> </td>");
document.write("        </tr>");
document.write("      </table></td>");
document.write("    <td width=\"11\" align=\"right\"><img src=\"http://www.topstudy.com.cn/images/newtop2.gif\" width=\"11\" height=\"79\"></td>");
document.write("  </tr>");
document.write("</table>");
