document.write("<style type=\"text/css\">");
document.write("<!--");
document.write("body {");
document.write("	margin-left: 0px;");
document.write("	margin-top: 0px;");
document.write("	margin-right: 0px;");
document.write("	margin-bottom: 0px;");
document.write("}");
document.write("#newtop1 {");
document.write("	FONT-SIZE: 12px; COLOR: #4D0095; LINE-HEIGHT: 160%; TEXT-DECORATION: none");
document.write("}");
document.write("#newtop1 A {");
document.write("	FONT-SIZE: 12px; COLOR: #4D0095; LINE-HEIGHT: 160%; TEXT-DECORATION: none");
document.write("}");
document.write("#newtop1 A:hover {");
document.write("	FONT-SIZE: 12px; COLOR: #ff9900; LINE-HEIGHT: 160%; TEXT-DECORATION: underline");
document.write("}");
document.write("#foot1 { color:#1F3A87; font-size:12px; line-height:160%; text-decoration:none}");
document.write("#foot1 a{ color:#1F3A87; font-size:12px; line-height:160%; text-decoration:none}");
document.write("#foot1 a:hover{ color:#ff3300; font-size:12px; line-height:160%; text-decoration:none}");
document.write("#foot2{ color:#000000; font-size:12px; line-height:160%; text-decoration:none}");
document.write("#foot2 a{ color:#000000; font-size:12px; line-height:160%; text-decoration:none}");
document.write("#foot2 a:hover{ color:#3300ff; font-size:12px; line-height:160%; text-decoration:underline}");
document.write("-->");
document.write("</style></head>");
document.write("<body>");
document.write("<table width=\"760\"  border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" bgcolor=\"#FFFFFF\">");
document.write("  <tr>");
document.write("    <td><table width=\"760\" border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\">");
document.write("      <tr>");
document.write("        <td width=\"12\"><img src=\"http://www.topstudy.com.cn/images/foot1.gif\" width=\"12\" height=\"31\"></td>");
document.write("        <td align=\"center\" bgcolor=\"#EFEFEF\" id=\"newtop1\"><strong>全国分站：</strong>|<a href=\"http://bj.topstudy.com.cn/\">北京</a> |<a href=\"http://sh.topstudy.com.cn/\">上海</a> |<a href=\"http://gz.topstudy.com.cn/\">广州</a> |<a href=\"http://cc.topstudy.com.cn/\">长春</a> |<a href=\"http://cq.topstudy.com.cn/\">重庆</a> |<a href=\"http://cs.topstudy.com.cn/\">长沙</a> |<a href=\"http://dl.topstudy.com.cn/\">大连</a> |<a href=\"http://hrb.topstudy.com.cn/\">哈尔滨</a> |<a href=\"http://hz.topstudy.com.cn/\">杭州</a> |<a href=\"http://ha.topstudy.com.cn/\">河南</a> |<a href=\"http://nj.topstudy.com.cn/\">南京</a> |<a href=\"http://qd.topstudy.com.cn/\">青岛</a> |<a href=\"http://sjz.topstudy.com.cn/\">石家庄</a> |<a href=\"http://sy.topstudy.com.cn/\">沈阳</a> |<a href=\"http://sz.topstudy.com.cn/\">深圳</a> |<a href=\"http://tj.topstudy.com.cn/\">天津</a> |<a href=\"http://xa.topstudy.com.cn/\">西安</a> |<a href=\"http://wh.topstudy.com.cn/\">武汉</a></td>");
document.write("        <td width=\"12\" align=\"right\"><img src=\"http://www.topstudy.com.cn/images/foot2.gif\" width=\"12\" height=\"31\"></td>");
document.write("      </tr>");
document.write("    </table>");
document.write("      <table width=\"500\" height=\"6\" border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\">");
document.write("        <tr>");
document.write("          <td></td>");
document.write("        </tr>");
document.write("      </table>");
document.write("      <table width=\"600\" height=\"34\" border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\">");
document.write("        <tr>");
document.write("          <td width=\"116\" align=\"center\"><a href=\"http://www.topstudy.com.cn/main/kefu/liuchengtu.asp\" target=\"_blank\"><img src=\"http://www.topstudy.com.cn/images/foot4.gif\" width=\"88\" height=\"27\" border=\"0\"></a></td>");
document.write("          <td width=\"1\"><img src=\"http://www.topstudy.com.cn/images/foot3.gif\" width=\"1\" height=\"34\"></td>");
document.write("          <td width=\"116\" align=\"center\"><a href=\"http://www.topstudy.com.cn/main/kefu/\" target=\"_blank\"><img src=\"http://www.topstudy.com.cn/images/foot5.gif\" width=\"97\" height=\"27\" border=\"0\"></a></td>");
document.write("          <td width=\"1\"><img src=\"http://www.topstudy.com.cn/images/foot3.gif\" width=\"1\" height=\"34\"></td>");
document.write("          <td width=\"116\" align=\"center\"><a href=# onClick=window.external.addFavorite('http://www.topstudy.com.cn','中国精品学习网')><img src=\"http://www.topstudy.com.cn/images/foot6.gif\" width=\"102\" height=\"27\" border=\"0\"></a></td>");
document.write("          <td width=\"1\"><img src=\"http://www.topstudy.com.cn/images/foot3.gif\" width=\"1\" height=\"34\"></td>");
document.write("          <td width=\"116\" align=\"center\"><a href=\"http://bbs.topstudy.com.cn/\" target=\"_blank\"><img src=\"http://www.topstudy.com.cn/images/foot7.gif\" width=\"99\" height=\"27\" border=\"0\"></a></td>");
document.write("          <td width=\"1\"><img src=\"http://www.topstudy.com.cn/images/foot3.gif\" width=\"1\" height=\"34\"></td>");
document.write("          <td width=\"116\" align=\"center\"><a href=\"http://www.topstudy.com.cn/main/shangwu/\" target=\"_blank\"><img src=\"http://www.topstudy.com.cn/images/foot8.gif\" width=\"99\" height=\"27\" border=\"0\"></a></td>");
document.write("        </tr>");
document.write("      </table>");
document.write("      <table width=\"500\" height=\"6\" border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\">");
document.write("        <tr>");
document.write("          <td></td>");
document.write("        </tr>");
document.write("      </table>");
document.write("      <table width=\"760\" height=\"20\" border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" id=\"foot1\">");
document.write("        <tr>");
document.write("          <td align=\"center\"><a href=\"http://www.topstudy.com.cn/main/shangwu/6-1.htm\" target=\"_blank\">About us</a> ─ <a href=\"http://www.topstudy.com.cn/main/shangwu/6.htm\" target=\"_blank\">网站简介</a> ─<a href=\"http://www.topstudy.com.cn/main/shangwu/2.htm\" target=\"_blank\"> 广告服务</a> ─ <a href=\"http://www.topstudy.com.cn/main/shangwu/11.htm\" target=\"_blank\">诚聘英才</a> ─<a href=\"http://www.topstudy.com.cn/main/shangwu/14.htm\" target=\"_blank\"> 团体培训</a> ─ <a href=\"http://www.topstudy.com.cn/main/shangwu/3.htm\" target=\"_blank\">联系我们</a> ─ <a href=\"http://www.topstudy.com.cn/main/shangwu/copyright.htm\">版权&amp;免责声明</a></td>");
document.write("        </tr>");
document.write("      </table>");
document.write("      <table width=\"760\" height=\"20\" border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" id=\"foot2\">");
document.write("        <tr>");
document.write("          <td align=\"center\"><strong><font color=\"#FF0000\">全国统一学习顾问热线：95105977</font></strong> 　　总部地址：北京市海淀区中关村南大街甲6号铸诚大厦A座915室(邮编：100086)</td>");
document.write("        </tr>");
document.write("      </table>");
document.write("      <table width=\"350\" height=\"30\" border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" id=\"foot2\">");
document.write("        <tr>");
document.write("          <td width=\"309\" align=\"center\"><strong>2001-2006 中国·精品学习网</strong>&nbsp; 京ICP证040590号</td>");
document.write("          <td width=\"41\" align=\"center\"><img src=\"http://www.topstudy.com.cn/images/foot9.gif\" width=\"28\" height=\"30\"></td>");
document.write("        </tr>");
document.write("      </table></td>");
document.write("  </tr>");
document.write("</table>");
