document.write("<SCRIPT language=JavaScript src=\"http://www.feloo.cn/js/setCity.js\" type=text/javascript></SCRIPT><LINK href=\"http://www.feloo.cn/css/setCity.css\" type=text/css rel=stylesheet>");
document.write("<style type='text/css'><!--.newtop1 {FONT-SIZE: 12px; COLOR: #000000; LINE-HEIGHT: 160%; TEXT-DECORATION: none}.newtop1 A {FONT-SIZE: 12px; COLOR: #000000; LINE-HEIGHT: 160%; TEXT-DECORATION: none}.newtop1 A:hover {FONT-SIZE: 12px; COLOR: #ff3300; LINE-HEIGHT: 160%; TEXT-DECORATION: none}.newtop3 {FONT-WEIGHT: bold;FONT-SIZE: 12px; COLOR: #BF0000; LINE-HEIGHT: 180%; TEXT-DECORATION: none}.newtop3 A {FONT-WEIGHT: bold;FONT-SIZE: 12px; COLOR: #BF0000; LINE-HEIGHT: 180%; TEXT-DECORATION: none}.newtop3 A:visited {FONT-WEIGHT: bold;FONT-SIZE: 12px; COLOR: #BF0000; LINE-HEIGHT: 180%; TEXT-DECORATION: none}.newtop3 A:hover {FONT-WEIGHT: bold;FONT-SIZE: 12px; COLOR: #ff3300; LINE-HEIGHT: 180%; TEXT-DECORATION: underline}.newtop4 {FONT-SIZE: 12px; COLOR: #ffffff; LINE-HEIGHT: 160%; TEXT-DECORATION: none}.newtop4 A {FONT-SIZE: 12px; COLOR: #ffffff; LINE-HEIGHT: 160%; TEXT-DECORATION: none}.newtop4 A:visited {FONT-SIZE: 12px; COLOR: #ffffff; LINE-HEIGHT: 160%; TEXT-DECORATION: none}.newtop4 A:hover {FONT-SIZE: 12px; COLOR: #ffff00; LINE-HEIGHT: 160%; TEXT-DECORATION: underline}--></style><TABLE WIDTH=778 BORDER=0 align='center' CELLPADDING=0 CELLSPACING=0><TR><TD COLSPAN=3><IMG SRC='http://www.feloo.cn/images0815/newtop_1.gif' WIDTH=778 HEIGHT=4 ALT=''></TD></TR><TR><TD><IMG SRC='http://www.feloo.cn/images0815/newtop_2.gif' WIDTH=9 HEIGHT=24 ALT=''></TD><TD width='760' background='http://www.feloo.cn/images0815/newtop_3.gif'><table width='100%' height='20'  border='0' cellpadding='0' cellspacing='0'><tr><td width='32%' class='newtop1' style='padding-left:5px;'><IMG SRC='http://www.feloo.cn/beijing/images/feloo1000.gif' WIDTH=68 HEIGHT=20 ALT=''>");
document.write("[<A class=CityMenuLink "
+"      id=MenuCity onmouseover=\"mcl(true,'MenuCityList', 'MenuCity', true);\"                      "
+"      onmouseout=\"mcl(false,'MenuCityList', 'MenuCity', true);\"                                  "
+"      href=\"http://www.feloo.cn/citylist/\"><span>切换城市</span></A>]                                                            "
+"      <DIV class=FlowMenuList id=MenuCityList                                                    "
+"      onmouseover=\"mcl(true,'MenuCityList', 'MenuCity', true);\"                                  "
+"      onmouseout=\"mcl(false,'MenuCityList', 'MenuCity', true);\">                                 "
+"      <TABLE>                                                                                    "
+"        <TBODY>                                                                                  "
+"        <TR>                                                                                     "
+"  <td><a href=\"http://www.feloo.cn/?city=010\"  target=\"_top\" class=\"B\">北京</a></td>           "
+"	<td><a href=\"http://www.feloo.cn/?city=021\"  target=\"_top\" class=\"B\">上海</a></td>             "
+"	<td><a href=\"http://www.feloo.cn/?city=022\"  target=\"_top\" class=\"B\">天津</a></td>             "
+"	<td><a href=\"http://www.feloo.cn/?city=027\"  target=\"_top\" class=\"B\">武汉</a></td>             "
+"	<td><a href=\"http://www.feloo.cn/?city=0531\" target=\"_top\" class=\"B\">济南</a></td>            "
+"	<td><a href=\"http://www.feloo.cn/?city=0755\" target=\"_top\" class=\"B\">深圳</a></td>            "
+"	<td><a href=\"http://www.feloo.cn/?city=0351\" target=\"_top\" class=\"B\">太原</a></td>            "
+"	<td><a href=\"http://www.feloo.cn/?city=0000\" target=\"_top\" class=\"B\">其他城市</a></td>        "
+"        </TR></TBODY></TABLE></DIV>"); 
document.write("<a href='http://www.feloo.cn/special/jiameng/' target='_blank' class='style10'>加盟地方站</a></td><td width='68%' align='center' class='newtop3'><a href='http://home.feloo.cn/community/' target='_blank'>社区</a> | <a href='http://home.feloo.cn/community/#bbs'>论坛</a> | <a href='http://home.feloo.cn/community/#society'>小组</a> | <a href='http://home.feloo.cn/community/#ask'>问吧</a> | <a href='http://home.feloo.cn/community/#resource'>资料 </a>| <a href='http://bang.feloo.cn/' target='_blank'>飞龙榜</a>| <a href='http://www.feloo.cn/about/allclass.htm' target='_blank'>课程总汇</a> | <a href='http://www.feloo.cn/help/' target='_blank'>客服中心</a> | <a href='http://www.feloo.cn/user/MyFeloo.jsp' target='_blank'>我的飞龙</a></td></tr></table></TD><TD><IMG SRC='http://www.feloo.cn/images0815/newtop_4.gif' WIDTH=9 HEIGHT=24 ALT=''></TD></TR><TR><TD height='28'><IMG SRC='http://www.feloo.cn/images0815/newtop_5.gif' WIDTH=9 HEIGHT=28 ALT=''></TD><TD width='760' background='http://www.feloo.cn/images0815/newtop_6.gif'><table width='100%' height='27'  border='0' cellpadding='0' cellspacing='0'><tr><td height='24' align='center' class='newtop4'><a href='http://www.feloo.cn' target='_blank'>首页</a> | <a href='http://english.bj.feloo.cn' target='_blank'>英语</a> | <a href='http://it.bj.feloo.cn' target='_blank'>计算机</a> | <a href='http://xyz.bj.feloo.cn' target='_blank'>小语种</a> | <a href='http://qygl.bj.feloo.cn' target='_blank'>企业管理</a> | <a href='http://xxpx.bj.feloo.cn' target='_blank'>休闲培训</a> | <a href='http://edu.bj.feloo.cn' target='_blank'>学历教育</a> | <a href='http://zypx.bj.feloo.cn' target='_blank'>职业培训</a> | <a href='http://youth.bj.feloo.cn' target='_blank'>0－18岁</a> | <a href='http://college.feloo.cn' target='_blank'>高校招生</a> | <a href='http://www.feloo.cn/yuancheng' target='_blank'>远程教育</a></td></tr></table></TD><TD><IMG SRC='http://www.feloo.cn/images0815/newtop_7.gif' WIDTH=9 HEIGHT=28 ALT=''></TD></TR></TABLE>")