var _S_JV_="webbug_meta_ref_mod_noiframe_async_fc_:8.44c";var _S_DPID_="-9999-0-0-1";var _S_DOMAINROOT="sina.com.cn";var _S_PW_=window;var _S_PWD_=_S_PW_.document;var _S_PWDL_=_S_PWD_.location;var _S_BN_=navigator;var _S_NAN_=_S_BN_.appName.indexOf('Microsoft Internet Explorer')>-1?'MSIE':_S_BN_.appName;var _S_NAV_=_S_BN_.appVersion;var _S_PREF_=_S_PWD_.referrer.toLowerCase();var _S_PURL_=_S_PWDL_.href.toLowerCase();var _SP_MPID_="";
var _S_PID_="";var _S_UNA_="UNIPROU";var _S_UID_="nick";var _S_SID_="Apache";var _S_GID_="SINAGLOBAL";var _S_IFW=640;var _S_IFH=480;var _S_SID_V="";var _S_GID_V="";try{if (_S_ET>=0){_S_ET=_S_ET;}else{var _S_ET=0;}}catch(e){var _S_ET=0;}var _S_EXT1="";var _S_EXT2="";var _S_MCLICK="F";
var _S_HTTP=_S_PURL_.indexOf('https')>-1?'https://':'http://';var _S_BCNDOMAIN="beacon.sina.com.cn";var _S_CP_RF=_S_HTTP+_S_BCNDOMAIN+"/a.gif";var _S_CP_RF_D=_S_HTTP+_S_BCNDOMAIN+"/d.gif";var _S_CP_FC=_S_HTTP+_S_BCNDOMAIN+"/fc.html";
var _S_DIV_="<div style='position:absolute;top:0;left:0;width:0;height:0;z-index:1'><div style='position:absolute;top:0;left:0;width:1;height:1;'><iframe id='SUDA_FC' src='' width=1 height=1 SCROLLING=NO FRAMEBORDER=0></iframe></div><div style='position:absolute;top:0;left:0;width:0;height:0;visibility:hidden' id='SUDA_CS_DIV'></div></div>";
_S_PWD_.write(_S_DIV_);
function _S_getAnchor(){_S_PURL_=_S_PWDL_.href.toLowerCase();var sA=_S_PURL_.indexOf("#");if (-1==sA){return "";}return _S_PURL_.substring(sA+1);}
function _S_gUCk(ckName){if (("undefined"==ckName)||(""==ckName))return "";var _S_PWDC_=_S_PWD_.cookie;var start=_S_PWDC_.indexOf(ckName+"=");if (-1==start){return "";} start=_S_PWDC_.indexOf("=", start)+1;var end=_S_PWDC_.indexOf(";", start);if (0 >=end){end=_S_PWDC_.length;}ckValue=_S_PWDC_.substring(start, end);return ckValue;}
function _S_sUCk(ckName,ckValue, ckdays){if(ckValue !=null){if(("undefined"==ckdays)||(null==ckdays)){_S_PWD_.cookie=ckName+"="+ ckValue+"; domain="+_S_DOMAINROOT+"; path=/";}else{var now=new Date();var time=now.getTime();time=time + 86400000*ckdays;now.setTime(time);time=now.getTime();_S_PWD_.cookie=ckName+"="+ckValue+"; domain="+_S_DOMAINROOT+"; expires="+now.toUTCString()+"; path=/";}}}
function _S_gMeta(MName){pMeta=_S_PWD_.getElementsByName(MName);if(pMeta.length>0){return pMeta[0].content;} else{return "";}}
function _S_gCid(){try {metaTxt=_S_gMeta("publishid");if(""!=metaTxt){pbidList=metaTxt.split(",");if(pbidList.length>0) {if(pbidList.length>=3){_S_DPID_="-9999-0-"+pbidList[1]+"-"+pbidList[2];}return pbidList[0];}} else{return "0";}} catch(e){return "0";}}
function _S_sSID(){_S_p2Bcn("",_S_CP_RF_D);} function _S_sSIDV(_s_sidv){if(""!=_s_sidv){_S_sUCk(_S_SID_,_s_sidv);}}
function _S_gsSID(){if(""!=_S_SID_){var sid=_S_gUCk(_S_SID_);if(""==sid){_S_sSID();}_S_SID_V=sid;return sid;}else{return "";}}
function _S_sGID(_s_gidv){if(""!=_s_gidv){_S_sUCk(_S_GID_,_s_gidv,3650);}}
function _S_gGID(){if(""!=_S_GID_){return _S_gUCk(_S_GID_);}else{return "";}}
function _S_IFC2GID(){var _S_ifc=_S_PWD_.getElementById("SUDA_FC");if(_S_ifc){_S_ifc.src=_S_CP_FC+"?a=g&n="+_S_GID_+"&r="+Math.random();}}
function _S_gsGID(){if(""!=_S_GID_){var gid=_S_gUCk(_S_GID_);if(""==gid){_S_IFC2GID();}return gid;}else{return "";}}
function _S_p2Bcn(strQuest,wb_url){var _sl_scsd=_S_PWD_.getElementById("SUDA_CS_DIV");if(null!=_sl_scsd){_sl_scsd.innerHTML="<img width=0 height=0 src='"+wb_url+"?"+strQuest+"gUid_"+Math.random()+"' border='0' alt='' />";}} 
function _S_gConType(){var contype="";try{_S_PWD_.body.addBehavior("#default#clientCaps");contype=_S_PWD_.body.connectionType;}catch(e){contype="unkown";} return contype;} 
function _S_isHome(){var cul="";var isH="";try{cul=_S_PURL_;_S_PWD_.body.addBehavior("#default#homePage");isH=_S_PWD_.body.isHomePage(cul)?"Y":"N";}catch(e){isH="unkown";} return isH;}
function _S_isFreshMeta(){var _s_head_=_S_PWD_.documentElement.innerHTML.substring(0,1024); var reg=new RegExp("<meta\\s*http-equiv\\s*=((\\s*refresh\\s*)|(\'refresh\')|(\"refresh\"))\s*content\s*=","ig"); return reg.test(_s_head_); }
function _S_isIFrameSelf(){if(_S_PW_.top==_S_PW_){return false;}else{try{if(_S_PWD_.body.clientHeight==0){return false;}if((_S_PWD_.body.clientHeight>=_S_IFH)&&(_S_PWD_.body.clientWidth>=_S_IFW)){return false;}else{return true;}}catch(e){return true;}}}
function _S_gJVer(){var p,appsign,appver,jsver=1.0,isN6=0;if ('MSIE'==_S_NAN_){appsign='MSIE';p=_S_NAV_.indexOf(appsign);if (p>=0){appver=parseInt(_S_NAV_.substring(p+5));if(3<=appver){jsver=1.1;if(4<=appver){jsver=1.3;}}}}else if(("Netscape"==_S_NAN_)||("Opera"==_S_NAN_)||("Mozilla"==_S_NAN_)){jsver=1.3;appsign='Netscape6';p=_S_NAV_.indexOf(appsign);if(p>=0){jsver=1.5;}}return jsver;}
function _S_gPageInfo(PageID,_sp_rfurl){return _S_gsSID()+"|pid:"+PageID+"|"+escape(_S_getAnchor())+"|st:0|et:"+_S_ET+"|"+escape(_sp_rfurl)+"|hp:"+_S_isHome()+"|lb:1|PGLS:"+_S_gMeta("stencil")+"|keys:"+_S_gMeta("keywords")+"|"+_S_EXT1+"|"+_S_EXT2+"|*|";}
function _S_gEnvInfo(){var now=new Date();return "sz:"+screen.width+"x"+screen.height+"||dp:"+screen.colorDepth+"||ac:"+_S_BN_.appCodeName+"||an:"+_S_NAN_+"||av:0||cpu:"+_S_BN_.cpuClass+"||pf:"+_S_BN_.platform+"||jv:"+_S_gJVer()+"||ct:"+_S_gConType()+"||lg:"+_S_BN_.systemLanguage+"||tz:"+now.getTimezoneOffset()/60;}
function _S_pBeacon(_sp_mpid,ext1,ext2,mc){try{if(("undefined"==_sp_mpid)||(""==_sp_mpid)){_sp_mpid=_S_gCid()+_S_DPID_;}if("undefined"==ext1){ext1="";}_S_EXT1=ext1;if("undefined"==ext2){ext2="";}_S_EXT2=ext2;if((_S_isFreshMeta())||(_S_isIFrameSelf())){return;}if(("1"!=mc)&&(_S_ET>0)){return;}_S_ET=_S_ET+1;_SP_MPID_=_sp_mpid;var sudsid=_S_gsGID();var ckValue=_S_gEnvInfo();var unStr=_S_gUCk(_S_UNA_);var uidStr=_S_gUCk(_S_UID_);var envStr="UNIPROINFO="+ckValue+"||un:"+unStr+"||uid:"+uidStr+";";var refUrl=_S_PREF_;var cPageStr=_S_gPageInfo(_SP_MPID_,refUrl);var lbStr=sudsid+"|*|"+cPageStr;lbStr=envStr+"UNIPROPATH="+lbStr+";";_S_p2Bcn(lbStr,_S_CP_RF);}catch(e){}}
function _S_pSt(_sp_mpid,ext1,ext2){try{_S_PW_.setTimeout("_S_gsSID()",500);_S_PW_.setTimeout("_S_pBeacon('"+_sp_mpid+"','"+ext1+"','"+ext2+"',0)",2000);_S_PW_.setTimeout("_S_rset()",60000);}catch(e){}}
function _S_pStM(_sp_mpid,ext1,ext2,mc){if("1"!=mc){mc="0";}_S_PW_.setTimeout("_S_pBeacon('"+_sp_mpid+"','"+ext1+"','"+ext2+"',"+mc+")",2000);}
function _S_rset(){if((""==_S_gUCk(_S_GID_))&&(""==_S_GID_V)){_S_GID_V=_S_gsGID();if(""==_S_GID_V){_S_PW_.setTimeout("_S_rset()",60000);}}}
